version: '2'

tasks:
  install-tools:
    silent: true
    cmds:
    - "$(cd $HOME && GO111MODULE=off go get github.com/onsi/ginkgo/ginkgo)"
    - "$(cd $HOME && GO111MODULE=off go get github.com/modocache/gover)"
    - "$(cd $HOME && GO111MODULE=off go get github.com/mattn/goveralls)"
  install:
    silent: true
    cmds:
    - go mod download
  test:
    silent: true
    cmds:
    - ginkgo -r -cover
  test-watch:
    silent: true
    cmds:
    - ginkgo watch -r
  lint:
    silent: true
    cmds:
    - golangci-lint run
  upload-coverage:
    silent: true
    cmds:
    - gover
    - goveralls -coverprofile=gover.coverprofile -service=travis-ci