version: '2'

tasks:
  install:
    silent: true
    cmds:
    - go mod download
  test:
    silent: true
    cmds:
    - ginkgo -r -cover
  test-watch:
    silent: true
    cmds:
    - ginkgo watch -r
  lint:
    silent: true
    cmds:
    - golangci-lint run
  collect-coverage:
    silent: true
    cmds:
    - gover
  upload-coverage:
    silent: true
    cmds:
    - goveralls service=travis-ci