version: '2'

tasks:
  install:
    silent: true
    cmds:
    - go mod download
  test:
    silent: true
    cmds:
    - ginkgo -r
  test-watch:
    silent: true
    cmds:
    - ginkgo watch -r
  lint:
    silent: true
    cmds:
    - golangci-lint run